### ISSUE TITLE
TODO for Raspple II next release

### ISSUE THREAD

**Issue by knghtbrd** [RasppleII/rasppleii#17]
* [X] Make A2SERVER scripts run from source directory
* [ ] Make A2CLOUD scripts run from source directory
  Partially done now, but it's hard to call this complete until a lot
  of stuff gets tested.
* [ ] Needed packages
  * [ ] cftp (#5)
  * [ ] oystter (#6)
  * [ ] gsport (#7)
  * [ ] linapple (#9)
  * [ ] nulib2 (#10)
  * [ ] undoit (#11)
  * [ ] unar backport? (#12)
  * [ ] netatalk2 (#8)
  * [ ] macipgw (#13)
  * [ ] ciopfs (#15)
  * [ ] appletalk kernel module? (#16)
* [ ] Fix screen/tmux bug
  Breaks the "screen run from fb console" test, which should not (and actually doesn't) work right anyway.
* [X] Remove the scriptURL thing, it's causing problems. :(
* [X] Transplant binaryURL items to blocksfree
* [ ] Develop upgrade/reinstallation/migration plan
* [ ] Fix Raspple II auto-login
* [ ] Finish pi-gen mods
* [ ] Create new slides
